-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 19:03:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyPorfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyPorfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyPorfolio` DEFAULT CHARACTER SET utf8 ;
USE `MyPorfolio` ;

-- -----------------------------------------------------
-- Table `MyPorfolio`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPorfolio`.`Persona` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Imagen` VARCHAR(255) NULL,
  `Presentacion` VARCHAR(255) NOT NULL,
  `TituloPerfil` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPorfolio`.`Educación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPorfolio`.`Educación` (
  `Id` INT NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_final` DATE NULL,
  `Titulo` VARCHAR(50) NOT NULL,
  `Logo` VARCHAR(255) NULL,
  `Institucion` VARCHAR(50) NOT NULL,
  `Persona_Id` INT NOT NULL,
  `Nivel` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`, `Persona_Id`),
  INDEX `fk_Educación_Persona_idx` (`Persona_Id` ASC),
  CONSTRAINT `fk_Educación_Persona`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `MyPorfolio`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPorfolio`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPorfolio`.`Experiencia` (
  `Id` INT NOT NULL,
  `Trabajo` VARCHAR(100) NOT NULL,
  `Puesto` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_final` DATE NULL,
  `Logo` VARCHAR(255) NULL,
  `Persona_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Persona_Id`),
  INDEX `fk_Experiencia_Persona1_idx` (`Persona_Id` ASC),
  CONSTRAINT `fk_Experiencia_Persona1`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `MyPorfolio`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPorfolio`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPorfolio`.`Habilidad` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Porcentaje` VARCHAR(50) NULL,
  `Persona_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Persona_Id`),
  INDEX `fk_Habilidad_Persona1_idx` (`Persona_Id` ASC),
  CONSTRAINT `fk_Habilidad_Persona1`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `MyPorfolio`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPorfolio`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPorfolio`.`Proyecto` (
  `Id` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Realizacion` DATE NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Persona_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Persona_Id`),
  INDEX `fk_Proyecto_Persona1_idx` (`Persona_Id` ASC),
  CONSTRAINT `fk_Proyecto_Persona1`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `MyPorfolio`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
